[package]
name = "guessing_game"
license = "MIT OR Apache-2.0"
version = "0.1.0"
description = "a game where you try to guess what number the computer has chosen."
edition = "2021"

[dependencies]
rand = "0.8.5"